### ISSUE TITLE
“unique”, "or" can not be highlighted

### ISSUE THREAD

**Issue by zhutmost** [mshr-h/vscode-systemverilog-support#12]
First thank you for developing this extension. 

Here is a small bug. Keyword <unique> and <or> cannot be highlighted correctly. 
eg. unique case,
      unique if, 
      always_ff@(posedge a or posedge b)

**Comment by mshr-h** [comment]
Thanks for reporting bug.
I'll fix it ASAP.

**Comment by mshr-h** [comment]
Fixed on version 0.0.9.
See below.

![screenshot](https://cloud.githubusercontent.com/assets/8973217/22780940/d8a251f8-ef03-11e6-9d4d-74e70c2366f8.png)

**Comment by zhutmost** [comment]
Great.
However, in your pictures, the colors of "?" in row 16-17 are not right.

**Comment by mshr-h** [comment]
I tried to fix the problem but I couldn't.
