### ISSUE TITLE
Goto Definition Feature Request

### ISSUE THREAD

**Issue by bjaminn** [mshr-h/vscode-systemverilog-support#28]
With the hover for pin definition it should be easy to make that the base of a 'go to definition' feature. Currently I do not have time to implement, but architectural it would be good to know if we just add all the functions of the language into a single class or make each one separate.

**Comment by popaflorin** [comment]
Is it possible to add this feature not only for pins and wires but for custom typdef data that is defined on a package in a different file? Sublime text seems to support this. If needed I can add an example.
