### ISSUE TITLE
unpacked arrays syntax highlighting isn't right

### ISSUE THREAD

**Issue by TheAustinSeven** [mshr-h/vscode-systemverilog-support#4]
The syntax for assigning a default value to an unpacked array `q = '{default:0};` currently interprets up to the next single quote as a string. The expected behavior would be to treat this similarly to `'0`. If you need any more details on what is wrong, I am more than happy to provide them.

**Comment by mshr-h** [comment]
Fixed.

**Comment by TheAustinSeven** [comment]
Thanks, I can confirm that it is working.
