### ISSUE TITLE
Matching problem on 'case endcase' inside 'begin end'

### ISSUE THREAD

**Issue by zinechant** [mshr-h/vscode-systemverilog-support#6]
It seems the 'case endcase' inside 'begin end' woud incur matching problem.
```
            always_comb begin
                case (NComBReg[NCi])
                    7'd01: NComBn[NCi] = 3'b000;
                    7'd02: NComBn[NCi] = 3'b001;
                    7'd04: NComBn[NCi] = 3'b010;
                    7'd08: NComBn[NCi] = 3'b011;
                    7'd16: NComBn[NCi] = 3'b100;
                    7'd32: NComBn[NCi] = 3'b101;
                    7'd64: NComBn[NCi] = 3'b110;
                    default: NComBn[NCi] = 3'b111;
                endcase
            end
```
The 'begin' would match to 'endcase'.

P.S. Thanks a lot for the developing! Have been using the extension a lot. Just found it updated, so come up to submit this issue.

**Comment by mshr-h** [comment]
I can't find the best solution.
But I can fix it if I unsupport 'begin ... end' matching.

**Comment by bjaminn** [comment]
I think this issue relates to this vscode issue and can be fixed when the vscode is fixed.
Microsoft/vscode#11856

**Comment by djoffe** [comment]
I submitted a new issue on VS Code that is more specifically referring to this.
https://github.com/Microsoft/vscode/issues/45324
