### ISSUE TITLE
Unpacked arrays syntax highlighting on multiple lines

### ISSUE THREAD

**Issue by djoffe** [mshr-h/vscode-systemverilog-support#9]
#4 has fixed unpacked array support when the closing bracket of the array is on the same line, but the same issue remains if if the closing bracket of the array is on a different line, such as:

```
assign mem_trx_ex = '{
      c_en     : mem_c_en         ,
      addr     : {mem_addr, 2'h0} ,
      default  : 'hX
   };
```

ps: Thanks for the extension :)

**Comment by mshr-h** [comment]
Fixed.

**Comment by djoffe** [comment]
Working like a charm :)
Thank you!
